### PR TITLE
Bug 1900125: Stop vendoring the module_utils/crypto.py Ansible library

### PR DESCRIPTION
**Pull request by timflannagan1**
Remove the module_utils (and as a result, the` module_utils.crypto.py` library) directory in the meteringconfig Ansible Role.

Previously, this was necessary in order to have Metering function on FIPS-enabled clusters as the crypto.py module was being referenced in the openssl-* Ansible modules, which we namely use for generating certificates for the components in the stack. This library listed the md5 algorithm as FIPS-compliant, despite md5 not being FIPS-compliant in many FIPS standards, which resulted in our Ansible role failing when attempting to call any of the openssl-* modules.

Now, this behavior has been patched upstream in Ansible (in versions greater than 2.9.6) so vendoring this library is no longer needed.

### CODE REVIEW

**Comment by timflannagan1** [comment]
I still need to test this on a FIPS-enabled cluster to verify whether this fixes the bug that's attached to this PR, in addition to whether that Ansible versioning pinning makes sense in the Dockerfile.metering-ansible-operator.

/hold

**Comment by timflannagan1** [comment]
Fired up a 4.6 FIPS-enabled cluster and verified these changes worked with a custom metering-ansible-operator image.

/hold cancel

**Comment by timflannagan1** [comment]
Fixes #1444

**Review by EmilyM1 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
