### PR TITLE
Add Dockerfile.metering-ansible-operator.rhel8

### PR DESCRIPTION
**Pull request by yselkowitz**
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.

### CODE REVIEW

**Comment by timflannagan1** [comment]
@yselkowitz I assume adding this Dockerfile is mainly a no-op until ocp-build-data is updated?

**Comment by yselkowitz** [comment]
Correct, and we're handling that part on behalf of all of OpenShift.

**Comment by timflannagan1** [comment]
Alright, sounds good.
/lgtm
/approve

**Comment by timflannagan1** [comment]
Need to make some changes due to the operator-sdk 0.19.x rebase landing downstream so e2e isn't broken
/hold

**Comment by timflannagan1** [comment]
Alright e2e should be functioning again
/hold cancel
/retest

**Pull request merged**
