### PR TITLE
hack,test: Deploy metering using the index image packaging method

### PR DESCRIPTION
**Pull request by timflannagan1**
Update the e2e.sh wrapper and the entrypoint to the e2e suite to consume an additional go test flag.

Note: in the case we're running e2e tests in a CI environment, both of the bundle and index images are ephemeral and won't be promoted. This means we cannot set a reasonable default value for the index image environment variable/flagset.

Makes minor changes in the way we expose the metering-ocp package that test installations can consume. Before, we spun up a local registry containing the old packagemanifest versioning. Now, with the introduction of index images and the depreciation of the packagemanifest/app-registry format, we can simply create a CatalogSource custom resource that points to an existing index image. We'll most likely need to continue iterating on this approach, and determine whether it makes sense to provide an avenue to deploy metering using both approaches. For now, this only uses the index image format.

### CODE REVIEW

**Comment by timflannagan1** [comment]
Ah judging by this output:
```
+ TEST_ENABLE_MACHINE_AUTOSCALING=true
+ TEST_OUTPUT_PATH=/tmp/artifacts/metering_test_output/e2e
+ EXTRA_TEST_FLAGS='-run TestManualMeteringInstall'
+ make e2e
go build -mod=vendor -ldflags '-extldflags "-static"' -o bin/deploy-metering github.com/kube-reporting/metering-operator/cmd/deploy-metering
hack/e2e.sh
```
It looks like we were testing against the previous CI configuration as there's no `+ METERING_ANSIBLE_OPERATOR_INDEX_IMAGE` variable being printed (due to `set -x` being present). Retesting anyways as I pushed a commit that echo's the output of that environment variable we're expecting.

**Comment by timflannagan1** [comment]
Looking at the console as the e2e tests run, it looks like the index image is being properly populated:
```

$METERING_NAMESPACE=metering
--
  | $METERING_RUN_TESTS_LOCALLY=false
  | $METERING_RUN_DEV_TEST_SETUP=false
  | $METERING_REPO_VERSION=4.6
  | $METERING_OLM_SUBSCRIPTION_CHANNEL=4.6
  | $METERING_OPERATOR_IMAGE_REPO=registry.svc.ci.openshift.org/ci-op-8hrs2rsm/stable
  | $REPORTING_OPERATOR_IMAGE_REPO=registry.svc.ci.openshift.org/ci-op-8hrs2rsm/stable
  | $METERING_OPERATOR_IMAGE_TAG=metering-ansible-operator
  | $REPORTING_OPERATOR_IMAGE_TAG=metering-reporting-operator
  | $METERING_ANSIBLE_OPERATOR_IMAGE_REGISTRY=registry.svc.ci.openshift.org/ci-op-8hrs2rsm/stable:metering-ansible-operator-registry
  | $METERING_ANSIBLE_OPERATOR_INDEX_IMAGE=registry.svc.ci.openshift.org/ci-op-8hrs2rsm/pipeline@sha256:3ddb183b4c40433e5bd3c2ff118bab8cae36fd62a6bd92f559e7a8f69588902e
  | $TEST_OUTPUT_PATH=/tmp/artifacts/metering_test_output/e2e
  | $TEST_RUN_ALL_INSTALL_TESTS=false
...
+ go test -test.short=false -test.v -parallel 10 -timeout 90m ./test/e2e -kubeconfig=/var/run/secrets/ci.openshift.io/multi-stage/kubeconfig -namespace-prefix=metering -test-output-path=/tmp/artifacts/metering_test_output/e2e -test-run-all-install-tests=false -log-level=debug -run-tests-local=false -repo-path=/go/src/github.com/kube-reporting/metering-operator -repo-version=4.6 -run-dev-setup=false -registry-image=registry.svc.ci.openshift.org/ci-op-8hrs2rsm/stable:metering-ansible-operator-registry -index-image=registry.svc.ci.openshift.org/ci-op-8hrs2rsm/pipeline@sha256:3ddb183b4c40433e5bd3c2ff118bab8cae36fd62a6bd92f559e7a8f69588902e -subscription-channel=4.6 -upgrade-from-subscription-channel=4.5 -run TestManualMeteringInstall
```

Should continue to monitor the e2e results, but this PR appears to be working at the surface.

**Comment by timflannagan1** [comment]
Manually adding the valid-bug label as this only effects test code and nothing user-facing.

**Comment by timflannagan1** [comment]
Actual tests passed but the must-gather step in CI failed (presumably due to the move to RHEL8 images):
```
Running must-gather...
error: gather did not start for pod must-gather-8p88q: resource name may not be empty
error: failed to execute wrapped command: exit status 1
```
/override ci/prow/metering-e2e-aws

**Review by EmilyM1 — APPROVED** [review]
/approve

**Comment by timflannagan1** [comment]
Looks like the changes made to the CI workflow are using m5.large AWS instances instead of the m5.xlarge that I assume we were still using. As a workaround for now, decrease the CPU requests for the reporting-operator, as `cpu: 1` is still fairly large, and shouldn't slow down e2e runs too much.

**Comment by timflannagan1** [comment]
Looks like I forgot to update the e2e upgrade test:
```
+ tee /tmp/artifacts/metering_test_output/upgrade/tests/e2e-tests.log
time="09-14-2020 21:51:53" level=info msg="Setting the log level to debug" app=deploy
time="09-14-2020 21:51:53" level=fatal msg="You need to specify a non-empty --index-image flag value" app=deploy
FAIL	github.com/kube-reporting/metering-operator/test/e2e	0.085s
FAIL
```
This will require some more involved changes, and I need to double-check if it's possible to either 1.) upgrade from the app-registry format to the index image one 2.) updating our CI configuration to also build and 4.5 bundle and attach that to the overall index image.

/hold

**Comment by timflannagan1** [comment]
It looks like the must-gather is still flaking like it was yesterday:
```
Running must-gather...
error: gather did not start for pod must-gather-hsltv: resource name may not be empty
error: failed to execute wrapped command: exit status 1
```

The actual upgrade test passed after the changes made to the CI configuration, so overriding that test.
/override ci/prow/metering-upgrade-aws

**Pull request merged**
